spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_management?useSSL=false&serverTimezone=UTC
    username: root
    password: MysqlPassword@1998
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
